### PR TITLE
Conversion for array index assignment

### PR DESCRIPTION
**Pull request by BrianFreemanAtlanta**
Link to issue(s) this covers
Closes Issue #365 
### Problem
Narrowing conversion from Object to string needed explicit ToString conversion added.

### Solution
* Added System.Collections to compilation options.  In second commit.  Can do separate PR if needed.
* Changed test to var declaration in C# instead of string declaration because it appears the converter prefers the var declaration.
* Added test case for simple object to string and more complex ListArray to string array assignment.

### CODE REVIEW

**Comment by GrahamTheCoder** [comment]
Great stuff. It didn't cause much faff this time, but to avoid conflicts in future, make sure you've fetched/pulled from origin (i.e. this repo), and start your branch from the latest master.
Thanks again!

**Comment by mrmonday** [comment]
Thank you for doing this, @BrianFreemanAtlanta!

Couple of vaguely related things:

 * If you're doing the `CHANGELOG` thing, you might want to add [merge=union](https://www.git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-union) to the `.gitattributes` to avoid merge conflicts
 * If we have the `.vbproj`, we should pull the global import options from there (`<Import Include="System" />` etc) instead of hard-coding the list.

**Comment by GrahamTheCoder** [comment]
Thanks @mrmonday . I'm totally on board with both of those. Please feel free to PR them.
If we made use of them from the compilation options here: https://github.com/icsharpcode/CodeConverter/blob/69fa87098ed194615e456ebe71f1d0704f9a17ee/ICSharpCode.CodeConverter/VB/NodesVisitor.cs#L105 then the hard-coded bit for when there's no vbproj could set them in compilation options rather than adding actual source text.

**Comment by BrianFreemanAtlanta** [comment]
Will do. I started from the master I just missed merging to the latest version before starting the new branch after completing my other pull request.
Brian



Sent from my Verizon, Samsung Galaxy smartphone

**Pull request merged**
