### PR TITLE
Switch to new spaproxy template from dotnet 6

### LINKED ISSUE #787: Web + Func update to .NET 6
A simple tfm change might not be the best way to do this - both for the Azure Function as well as the Web project. For Azure Functions:

https://techcommunity.microsoft.com/t5/apps-on-azure/azure-functions-4-0-and-net-6-support-are-now-generally/ba-p/2933245

For the Web, SPA-integration has changed considerably, so a File New/Project and copy/paste from the old to the new might be best.

https://docs.microsoft.com/en-us/aspnet/core/release-notes/aspnetcore-6.0?view=aspnetcore-6.0#miscellaneous

### PR DESCRIPTION
**Pull request by GrahamTheCoder**
Fixes #787

When running in visual studio, the Web project is now really just a (semi-)convenient debug tool to:
* Start the webpack dev server
* Host a version of the API

When published, and run in IIS it:
* Hosts the built static files
* Host a version of the API

### Before merge 

* [x] Ensure both nuget packages get 3 ticks in nuget package explorer
image

### CODE REVIEW

**Comment by christophwille** [comment]
Yes, we can host on GH pages, might actually be a good idea (alternatively: Azure Static Web Apps, we do that with a custom copy of release stats here https://github.com/christophwille/github-release-stats)

**Comment by GrahamTheCoder** [comment]
I've just tested it in IIS and it does work by magic (i.e. it doesn't try to run the webpack dev server)
So we can still do either mode as before

**Comment by GrahamTheCoder** [comment]
Azure static app sounds good (in some ways the github pages approach of having a branch in the repo with the built code is a bit ugly)

**Comment by christophwille** [comment]
If we publish to whereever - should that on "release"? Something like https://github.com/icsharpcode/ilspy-vscode/blob/master/.github/workflows/ci.yml#L46 or more elaborate https://github.com/icsharpcode/SharpZipLib/blob/master/.github/workflows/release.yml

**Comment by GrahamTheCoder** [comment]
Ah yeah that'd be really cool. I've created an issue for it here: https://github.com/icsharpcode/CodeConverter/issues/795

**Pull request merged**
