### PR TITLE
Static app from default template

### PR DESCRIPTION
**Pull request by GrahamTheCoder**
We'd like to turn the UI into a static site that can be hosted on GitHub pages for simplicity, that calls azure functions to do the conversion.

In preparation for https://github.com/icsharpcode/CodeConverter/issues/546 and #625

WIP - I've picked the most commonly used of the default Visual Studio Single Page App templates and started porting the site to it.

### CODE REVIEW

**Comment by christophwille** [comment]
I was thinking more of VS Code than VS. And using plain JS tooling.

**Comment by GrahamTheCoder** [comment]
The (untested) intent was that the csproj is just a convenient way to integrate into the build pipeline and makes the debug button in vs work for a convenient dev experience alongside the other bits. Using vscode and running npm start in the client app folder should work just as well.

**Comment by GrahamTheCoder** [comment]
I.e. I'm refactoring to something we could either deploy exactly as we do now, or repoint the api requests and deploy to github pages.

**Comment by GrahamTheCoder** [comment]
I'm busy the next few days, but should be able to finish this next week

**Comment by GrahamTheCoder** [comment]
I've added a readme explaining the options for running the site:
https://github.com/icsharpcode/CodeConverter/blob/master/Web/ClientApp/README.md

Let's discuss further development down this route on #625

**Pull request merged**
