### PR TITLE
Build GH Action Build matching Azure DevOps Pipeline

### PR DESCRIPTION
**Pull request by christophwille**
I have not matched https://github.com/icsharpcode/CodeConverter/blob/master/azure-pipelines.yml#L57 (necessary???)

First run artifacts:

https://github.com/icsharpcode/CodeConverter/actions/runs/586676519#artifacts

Note that GH re-zips automatically for download (no way around this behavior) and that artifacts can be downloaded only when you are logged in to GH.

Build passing badge can be built for master/succeeded once merged. TODO after merge: delete azure-pipelines.yml & pipeline on Azure DevOps.

Please squash-merge.

### CODE REVIEW

**Comment by GrahamTheCoder** [comment]
Looks good. Just the code conv tool nuget package missing that I can see. The runsettings from the line mentioned just set up the code coverage to be a vaguely useful number so we can see if things are going down hill (not that I've ever really checked it)

**Comment by christophwille** [comment]
https://github.com/icsharpcode/CodeConverter/blob/master/azure-pipelines.yml#L62 ah, that mislead me into thinking it wasn't packed and wouldn't need to be collected. Wrong.

screenshot from Azure DevOps

**Comment by christophwille** [comment]
Now we got all three: https://github.com/icsharpcode/CodeConverter/actions/runs/588190266#artifacts

**Comment by GrahamTheCoder** [comment]
@christophwille Before I delve into it, any guesses on why this is having issues now: https://github.com/icsharpcode/CodeConverter/runs/2264078251

**Comment by christophwille** [comment]
That one issue we already ran into with ILSpy; however, the restore problem... I don't know (yet; and I am not sure if it is really 100% a gh actions issue).

**Comment by GrahamTheCoder** [comment]
Thanks that's definitely helped. I think the remaining issue is now because vs isn't on the machine anymore, or the wrong version

**Comment by christophwille** [comment]
VS is on the machine, but it is now 16.9 (it was 16.8 previously - given the messages in the actions log something did change)

**Pull request merged**
