### PR TITLE
Property with modifier

### PR DESCRIPTION
**Pull request by BrianFreemanAtlanta**
working on issue #92 .  This handles the modifiers for the property accessors.  The test is currently failing because the accessor bodies are still empty.  

### Problem

working on accessors with individual modifiers on them with no code body to convert.

### Solution
* I added a new tokenContext for Member in Property
* I'm stumbling a bit to create the local declaration and accessor bodies when needed.
* I added tests for both directions C# -> VB and VB -> C# for the accessor modifiers
* I added code in CommonConversion to add required declarations for property blocks similar to pattern expressions and some declaration statements
* I updated convertAccessor to fill in the accessor body when needed

Tasks for this PR:
- [x] Recognize and carry over accessor modifiers when needed
- [x] Fill in required body when needed

I ran all the tests and made corrections so the property block modifiers come over only when needed and the existing tests still pass.

### CODE REVIEW

**Comment by GrahamTheCoder** [comment]
Looks like a good start. Have a look at the conversion in the other direction which probably has something similar. And try out roslyn quoter (link in the contributing.md file) if you haven't already for help generating specific structures. I'll try to add more specific tips if I get a minute later.

**Comment by BrianFreemanAtlanta** [comment]
Just in case it didn't let you know.  I checked in an update that completes both part of the problem.  You can review and let me know if I need to make any changes.

**Comment by GrahamTheCoder** [comment]
Sorry I couldn't be more help recently, but I've just now returned home to the land of Internet so I'll try to take a good look tomorrow. Great job making progress with minimal help!

**Comment by GrahamTheCoder** [comment]
All looks good, I've just pushed a few minor tidyups. The one I'm least sure about was removing the test for the vb->cs direction. Let me know if that was supposed to stay. Thanks for your work!

**Comment by BrianFreemanAtlanta** [comment]
Removing the extra test is fine.  I initially added it to confirm it was happening both directions, which it was.  That then confirmed for me that it was a full solution.

**Pull request merged**
